StaffStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StaffStore.Domain.Abstract;

namespace StaffStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductsRepository repository;
        public NavController(IProductsRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                                    .Select(x => x.Category)
                                    .Distinct()
                                    .OrderBy(x => x);
            return PartialView("FlexMenu", categories);
        }
    }
}

StaffStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StaffStore.Domain.Abstract;
using StaffStore.Domain.Entities;
using StaffStore.WebUI.Models;

namespace StaffStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductsRepository repository;
        public int PageSize = 4;

        public ProductController(IProductsRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        repository.Products.Count() :
                        repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

StaffStore.WebUI/Views/Shared/ProductSummary.Mobile1.cshtml
@model StaffStore.Domain.Entities.Product

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>
        @Model.Name
    </h2>
    <div>
        <div>
            @Model.Description
        </div>
        <div>
            <strong>(@Model.Price.ToString("c"))</strong>
        </div>
        <div>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.ProductID)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Add to cart" />
            }
        </div>
    </div>
</div>

StaffStore.WebUI/Views/Shared/ProductSummary.cshtml
@model StaffStore.Domain.Entities.Product


    <div class="well">
             @if (Model.ImageData != null)
            {
                <div class="pull-left" style="margin-right: 5px">
                    <img class="img-responsive" width="200" height="200" src="@Url.Action("GetImage", "Product", new { Model.ProductID})" />
                </div>

            }

            <h3>
                <strong>@Model.Name</strong>
            </h3>
            <div class="pull-right">
                <h3>
                    <span class="label label-primary">@Model.Price.ToString("c")</span>
                </h3>

                @using (Html.BeginForm("AddToCart", "Cart"))
                {
                    @Html.HiddenFor(x => x.ProductID)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Add to cart" />
                }
            </div>

            <span class="lead">@Model.Description</span>
    </div>

StaffStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="∼/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@*@ViewBag.Title*@</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

StaffStore.WebUI/Views/Shared/_Layout.Mobile1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script async defer src="https://maps.googleapis.com/maps/api/js?&key=AIzaSyDA6N6tGUD5k6riEeXQsKtyp70PxYq1rLc&callback=initMap&language=en"></script>
    <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>
                @Html.ActionLink("Staff Store", "List", "Product")
                <br />
                @Html.ActionLink("Contacts", "Contact", "Home")
            </h3>
            @Html.Action("Summary", "Cart")   
            @Html.Action("Menu", "Nav")
        </div>  
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StaffStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?&key=AIzaSyDA6N6tGUD5k6riEeXQsKtyp70PxYq1rLc&callback=initMap&language=en"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title - Staff Store</title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 5px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Staff Store", "List", "Product", null, new { @class = "navbar-brand" })
            </div>
            @Html.Action("Summary", "Cart")
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "List", "Product")</li>
                    <li>@Html.ActionLink("Contacts", "Contact", "Home")</li>
                    <li>@Html.ActionLink("About us", "About", "Home")</li>
                    <li>@Html.ActionLink("Payment and delivery", "Payment", "Home")</li>
                </ul>
             </div>
        </div>
    </div>
            <div class="visible-xs">
                @Html.Action("Menu", "Nav", new { horizontalLayout = true })
            </div>
            <div class="row panel">
                <div id="categories" class="col-xs-3 hidden-xs">
                    @Html.Action("Menu", "Nav")
                </div>
                <div class="col-xs-12 col-sm-8">
                    @RenderBody()
                    <br />
                    <hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - Demchenko Aleksandr</p>
                    </footer>
                </div>
            </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
</body>
</html>